# Site settings
title: Imsara Samarasinghe's Portfolio
description: This is my portfolio of all my engineering projects to date. I will be posting projects I completed while at Imperial College London and those I completed after leaving university.
url: "https://imsarasamarasinghe.github.io"
baseurl:

# Build settings
# theme: jekyll-theme-minimal

profile_image: "GitHubProfile.jpg"
